config/routes.rb
Rails.application.routes.draw do

  resources :merchants, except: [:create, :new, :show], format: false
  resources :transactions, only: [:index], format: false

  get "/500", to: "errors#internal_error"

  namespace :api do # TODO: consider using condition ->(req) { req.format.in? %i[json xml] }
    namespace :v1 do
      post "transactions", to: "transactions#create", format: false
    end
  end

end

app/models/merchant.rb
class Merchant < ApplicationRecord

  enum status: { active: "active", inactive: "inactive" }, _prefix: "status"

  belongs_to :user, inverse_of: :merchant, required: true
  has_many :transactions, inverse_of: :merchant

  scope :those_active, -> { where(status: "active") }

  validates :email, format: { with: ::URI::MailTo::EMAIL_REGEXP }

  def is_active
    self.status == "active"
  end

  def is_active=(bool)
    self.status = ActiveRecord::Type::Boolean.new.cast(bool) ? "active" : "inactive"
  end

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  before_action :set_merchant, only: [:edit, :update, :destroy]

  # GET /merchants
  def index
    @merchants = Merchant.includes(:user)
  end

  # GET /merchants/1/edit
  def edit
  end

  # PATCH/PUT /merchants/1
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to merchants_path, notice: "Merchant was successfully updated." }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: "Merchant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    def merchant_params
      params.require(:merchant).permit(:name, :email, :is_active, :description)
    end
end

app/views/merchants/_form.html.slim
= form_for @merchant do |f|
  - if @merchant.errors.any?
    #error_explanation
      h2 = "#{pluralize(@merchant.errors.count, "error")} prohibited this merchant from being saved:"
      ul
        - @merchant.errors.full_messages.each do |message|
          li = message

  .form-group.row
    label.col-sm-2.col-form-label Name
    .col-sm-10
      = f.text_field :name, class: "form-control form-control-sm", placeholder: ""

    label.col-sm-2.col-form-label Email
    .col-sm-10
      = f.text_field :email, class: "form-control form-control-sm", placeholder: ""

    .col-sm-2
    .col-sm-10
      .custom-control.custom-checkbox.mb-3
        = f.check_box :is_active, class: "custom-control-input", id: "is_active"
        label.custom-control-label for="isActive" Merchant is active
    .form-group.col-sm-12
      label Description
      = f.text_area :description, class: "form-control"

  = button_tag type: "submit", class: "btn btn-primary", id: "update_action" do
    i class="fa fa-save"
    |  Update merchant

app/views/merchants/edit.html.slim
h1 class="h1" Editing merchant

== render "form"

br

=< link_to merchants_path, class: "btn btn-secondary" do
  i class="fa fa-list"
  |  Back to the list

app/views/merchants/index.html.slim
h1.h1 Merchants

table.table.table-dark.table-striped id="merchants_list"
  thead
    tr
      th scope="col"
      th scope="col" User ID
      th scope="col" Name
      th scope="col" Email
      th scope="col" Description
      th scope="col"

  tbody
    - @merchants.each do |merchant|
      tr
        th
          = link_to edit_merchant_path(merchant), class: "btn btn-secondary", id: "edit_merchant_#{merchant.id}_link" do
            i.fa.fa-edit
        th scope="row" = merchant.user.id
        td = merchant.name
        td = merchant.email
        td = merchant.description
        td
          = link_to merchant, method: :delete, class: "btn btn-danger" do
            i.fa.fa-times